name: VirtualCoach
version: 1.0.0+2
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0

  # BLE
  polar:
    path: packages/polar
  flutter_blue_plus:
    path: packages/flutter_blue_plus
  flutter_blue: ^0.8.0
  # State Management
  get: ^4.6.5

  # Preferences
  shared_preferences: ^2.2.0

  # Generator
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.5
  image: ^4.0.17

  # UI
  flutter_svg: ^2.0.7
  lottie: ^2.4.0
  syncfusion_flutter_charts: ^21.2.6
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  horizontal_picker: ^1.2.0
  
  image_picker: ^1.0.1
  video_player: ^2.7.0

  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  vibration: ^1.8.1
  keep_screen_on: ^2.1.0

  # Notifications
  flutter_local_notifications: ^15.1.0+1
  logger: ^2.0.1

  # Firebase & Analytics
  firebase_performance: ^0.9.2+5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  # health: ^8.0.0
  syncfusion_flutter_gauges: ^21.2.10
  circular_countdown_timer: ^0.2.3
  firebase_auth: ^4.19.3
  cloud_firestore: ^4.17.1
  fluttertoast: ^8.2.5
  audioplayers: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/Logo.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/images/avatar/
    - assets/images/icons/
    - assets/animations/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
