// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vhpIG7uXUwGJVpcB-8nlhTzHOxXFA0U',
    appId: '1:295502453339:android:f06e2ad15ce7a249a3fd7e',
    messagingSenderId: '295502453339',
    projectId: 'app-polar-h10-3afd1',
    databaseURL: 'https://app-polar-h10-3afd1-default-rtdb.firebaseio.com',
    storageBucket: 'app-polar-h10-3afd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Q95LhHIy3WMwBfek_SS55jjkxtTgIxE',
    appId: '1:295502453339:ios:d11e2f6592226179a3fd7e',
    messagingSenderId: '295502453339',
    projectId: 'app-polar-h10-3afd1',
    databaseURL: 'https://app-polar-h10-3afd1-default-rtdb.firebaseio.com',
    storageBucket: 'app-polar-h10-3afd1.appspot.com',
    iosBundleId: 'com.hatofit.hatofit',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07QpfqJwlrIoNtwAN5AuQjOlUlqzXld0',
    appId: '1:295502453339:web:4ccbec595d320d1aa3fd7e',
    messagingSenderId: '295502453339',
    projectId: 'app-polar-h10-3afd1',
    authDomain: 'app-polar-h10-3afd1.firebaseapp.com',
    databaseURL: 'https://app-polar-h10-3afd1-default-rtdb.firebaseio.com',
    storageBucket: 'app-polar-h10-3afd1.appspot.com',
    measurementId: 'G-KCY8MJN4MR',
  );

}